### ISSUE TITLE
Use `hassioaddons/qemu-user-static` Docker container to setup binfmt

### ISSUE THREAD

**Issue by frenck** [hassio-addons/build-env#43]
# Problem/Motivation

At this moment, there is some "hacky" code in the build environment to setup `binfmt`.
We released a Docker container that can handle that:

https://github.com/hassio-addons/qemu-user-static

## Proposed changes

Replace the `binfmt` initialization code with a run of the above listed Docker container.

**Comment by frenck** [comment]
Merged into `master` branch.

**Comment by bbinet** [comment]
I don't really understand the reasoning behind this change: why not use update-binfmts (from binfmt-support debian package) here rather than calling a different docker which seem to mimic the work done by update-binfmts?
Is it to fix some bugs in update-binfmts, or are there any other reasons?

**Comment by frenck** [comment]
There are multiple reasons behind this.

First of all, bugs is one. There are known bugs in older versions with aarch64, which we encountered. Secondly, the created Docker image is really tiny and does the job in a limited but sufficient way. 

It mimics the way the multiarch project does this as well (and they provide a lot of Docker images for different architectures, some are actually supported by the main distro's).

I do not see any harm in this, since we now have a repository we can control and test ourselves, and do no longer rely on slow upstream updates and/or faulty packages.

Let me be clear on this, this is not the first time Qemu stuff broke.

**Comment by bbinet** [comment]
OK, I understand. Thanks for your answer.

On Tuesday, January 16, 2018, Franck Nijhof <notifications@github.com>
wrote:
> There are multiple reasons behind this.
>
> First of all, bugs is one. There are known bugs in older versions with
aarch64, which we encountered. Secondly, the created Docker image is really
tiny and does the job in a limited but sufficient way.
>
> It mimics the way the multiarch project does this as well (and they
provide a lot of Docker images for different architectures, some are
actually supported by the main distro's).
>
> I do not see any harm in this, since we now have a repository we can
control and test ourselves, and do no longer rely on slow upstream updates
and/or faulty packages.
>
> Let me be clear on this, this is not the first time Qemu stuff broke.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/nndqmY8LJM7iim7M8FXIylW_58jOvh1k2-gDk-nZEbCQYJqwzcuE1ECzR1v_7B4U_hVcBgWQlz4jC2VXERzwOu5hNEDO38Y24gknSEDnQwtNvXyzsVm72tKf_mZ5uBYrug6E5H-jUnggJX7dyHf_yG6G6I-nAA=s0-d-e1-ft#https://github.com/notifications/beacon/AAEp-Z7O1uYanwVX0jA0Io5G9Bt4tx7Rks5tLPzBgaJpZM4Q8qki.gif>
