### ISSUE TITLE
BUILD_FROM: unbound variable

### ISSUE THREAD

**Issue by korylprince** [hassio-addons/build-env#48]
# Problem/Motivation

Trying to build an image fails with:

`/usr/bin/build.sh: line 1149: BUILD_FROM: unbound variable`

## Expected behavior

The build should work.

## Steps to reproduce

Try to build an image without including the `--from` flag

## Workaround

Specify the base image with `--from`

**Comment by frenck** [comment]
Sorry for the long long wait...
Issue has been fixed in the master branch and will be in the next release.

Thanks, again, for the report and taking the time for creating this issue 👍
