### ISSUE TITLE
DOCKER_SQUASH: unbound variable

### ISSUE THREAD

**Issue by danielwelch** [hassio-addons/build-env#51]
# Problem/Motivation

Trying to build an image fails with:
`/usr/bin/build.sh: line 1122: DOCKER_SQUASH: unbound variable`

## Expected behavior

The image builds

## Actual behavior

The build fails during preflight checks  with above error.

## Steps to reproduce

I'm not really sure. This is happening consistently with a new add-on that I'm working on, both on [travis](https://travis-ci.org/danielwelch/hassio-zigbee2mqtt/builds/377399848) and when I attempt to build locally [repo](https://github.com/danielwelch/hassio-zigbee2mqtt).

Here is the build script I use:
```bash
docker run -it --rm --privileged --name ${ADDON_NAME} \
        -v ~/.docker:/root/.docker \
        -v "$(pwd)":/docker \
        hassioaddons/build-env:latest \
        --target ${ADDON_NAME} \
        --git \
        --all \
        --from "homeassistant/{arch}-base" \
        --author "Daniel Welch <dwelch2102@gmail.com>" \
        --doc-url "${GITHUB_URL}"
        --login ${DOCKER_USERNAME}
        --password ${DOCKER_PASSWORD}
```

However, I cannot reproduce this behavior when running the script locally on another [add-on](https://github.com/danielwelch/hassio-dropbox-sync) that I have developed.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by danielwelch** [comment]
caused by a typo on my end in my `config.json`, sorry

**Comment by frenck** [comment]
Stuff happens 👍 
Nevertheless, thanks for reporting.
