### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by frenck** [hassio-addons/build-env#52]
# Problem/Motivation

This build environment isn't used by the community add-ons anymore.
Everything is replaced by GitLab CI

## Proposed changes

- Add deprecation warnings
- Remove CI/CD
- Archive GitHub repository

**Comment by frenck** [comment]
Yeah I should..

**Comment by timelf123** [comment]
Can I use this to build my own addons or should I look at your CI examples instead?

**Comment by frenck** [comment]
My CI samples, require custom GitLab CI servers (native machines).

Home Assistant provides cross architecture build tools, please use those.
